### ISSUE TITLE
Company conda-forge mirror usage

### ISSUE THREAD

**Issue by quartox** [regro/conda-metachannel#20]
I tried using this at my company but we use an internal mirror to connect to conda-forge and I couldn't get it to work. I tried replacing all of the urls I could find in the code to my mirror url but it also failed. Any suggestions or improvement ideas for making this work with a mirror?

I have time to submit a PR if you can help me get started on what needs to be changed.

**Comment by scopatz** [comment]
What is the error you are seeing?  Also how are you trying to run this?

**Comment by quartox** [comment]
Should have mentioned that they explicitly turned off external internet access to our servers for security reasons. The original error is 

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f219b636a58>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I will try removing all `anaconda.org` urls that I find. I already changed the `CHANNEL_MAP` to point to the mirror.

**Comment by scopatz** [comment]
That sounds like the right strategy, though it really depends on how the mirror they are running functions,

**Comment by quartox** [comment]
Got it working this time changing the `url_prefix` in `graph.py` (not sure why I failed a few weeks ago, but at least it is working now). Would it make sense to add an argument for this or is this an edge case?

Also, is there an important difference between the `CHANNEL_MAP` url and the `url_prefix`?

**Comment by scopatz** [comment]
> Would it make sense to add an argument for this or is this an edge case?

Yes, absolutely.  As long as the default remains to point to anaconda.org.  Please feel free to put in a PR.  We can cut a release once it is merged.

> Also, is there an important difference between the CHANNEL_MAP url and the url_prefix?

I think that this is for the default case.

**Comment by quartox** [comment]
I am running into problems running it on my macbook. It lists 

```
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: conda-forge/pandas
  channel url: http://127.0.0.1:20124/conda-forge/pandas
  error code: 403
```

for code that works on linux. The only message on the command line when starting the server is

`cat: /proc/1/sched: No such file or directory`

I have limited experience with flask so I can't tell if this is helpful. I will submit a PR even if I can only get it to work on linux.

**Comment by scopatz** [comment]
locally, you might need to use `0.0.0.0`, instead of `127.0.0.1`

**Comment by quartox** [comment]
I still can't get it to work on my macbook. Might be due to security software installed by my company, but I keep getting a forbidden 403 error regardless of what host I choose.

It does, however, continue to work on our linux servers.

**Comment by scopatz** [comment]
hmm weird!

**Comment by quartox** [comment]
#21 

I had one more question: is the https://metachannel.conda-forge.org url stable enough that I could have a mirror to that created at my company?

**Comment by scopatz** [comment]
Yep, that is the stable URL

**Comment by scopatz** [comment]
Do you want us to do a release now?

**Comment by quartox** [comment]
Sure, sounds good to me.

**Comment by scopatz** [comment]
done!
